"""Stable, user-facing vocabulary for the audit trail.

Keep these labels separate from templates so recording and rendering use the
same definitions.  Database identifiers stay unchanged.
"""

ACTION_LABELS = {
    "CREATE": "Создано",
    "UPDATE": "Изменено",
    "DELETE": "Удалено",
    "STATUS_CHANGE": "Смена статуса",
    "FILE_UPLOAD": "Загружен файл",
    "FILE_DELETE": "Удалён файл",
    "FILE_RESTORE": "Восстановлен файл",
    "COPY": "Копирование заказа (активация д.с.)",
    "LOGIN": "Вход в систему",
}

ENTITY_FILTERS = {
    "organization": ("Организация", {"organization"}),
    "contract": ("Договор", {"contract"}),
    "additional_agreement": ("Доп. соглашение", {"additional_agreement"}),
    "application": ("Заявка", {"application"}),
    "order": ("Строка заказа", {"order", "order_item", "annual_demand", "specialty"}),
    "document": ("Файл", {"document", "document_attachment", "excel_import"}),
    "faculty": ("Факультет", {"faculty", "contract_faculty", "application_faculty"}),
    "app_user": ("Пользователь", {"app_user"}),
    "app_setting": ("Настройки", {"app_setting"}),
}

FIELD_LABELS = {
    "organization_id": "Организация",
    "contract_id": "Договор",
    "application_id": "Заявка",
    "additional_agreement_id": "Доп. соглашение",
    "previous_agreement_id": "Предыдущее доп. соглашение",
    "previous_order_id": "Предыдущая редакция заказа",
    "order_id": "Заказ",
    "order_item_id": "Строка заказа",
    "specialty_id": "Специальность",
    "faculty_id": "Факультет",
    "created_by": "Создал",
    "updated_by": "Изменил",
    "uploaded_by": "Загрузил",
    "document_id": "Документ",
    "number": "Номер",
    "name": "Наименование",
    "short_name": "Краткое наименование",
    "full_name": "Полное наименование",
    "unp": "УНП",
    "legal_address": "Юридический адрес",
    "authority": "Ведомство",
    "phone": "Телефон",
    "status": "Статус",
    "start_date": "Дата начала",
    "end_date": "Дата окончания",
    "date": "Дата",
    "received_date": "Дата получения",
    "signed_date": "Дата подписания",
    "activated_at": "Дата активации",
    "is_current": "Действующая редакция",
    "qualification": "Квалификация",
    "qualification_value": "Квалификация",
    "profile": "Профиль",
    "year": "Год",
    "quantity": "Потребность",
    "code": "Код",
    "faculty": "Факультет",
    "type": "Тип документа",
    "file_id": "Сохранённый файл",
    "original_filename": "Имя файла",
    "filename": "Имя файла",
    "stored_name": "Сохранённый файл",
    "file_kind": "Назначение файла",
    "original_name": "Имя файла",
    "mime_type": "Формат файла",
    "size_bytes": "Размер, байт",
    "deleted_at": "Дата удаления",
    "rows_processed": "Обработано строк",
    "organizations_created": "Создано организаций",
    "contracts_created": "Создано договоров",
    "faculty_links_created": "Добавлено факультетов",
    "order_items_created": "Добавлено строк заказа",
    "username": "Логин",
    "password": "Пароль",
    "role": "Роль",
    "is_active": "Активен",
    "must_change_password": "Требуется сменить пароль",
    "last_login_at": "Последний вход",
    "key": "Параметр",
    "value": "Значение",
    "description": "Описание",
    "source_order_id": "Исходный заказ",
    "target_order_id": "Новый заказ",
    "rows_count": "Скопировано строк",
}

VALUE_LABELS = {
    "ACTIVE": "Активен",
    "CLOSED": "Закрыт",
    "CURRENT": "Действующий",
    "SIGNED": "Подписан",
    "CONTRACT": "Договор",
    "APPLICATION": "Заявка",
    "ADDITIONAL_AGREEMENT": "Доп. соглашение",
    "signed_scan": "Подписанный скан",
    "generated_docx": "Сформированный документ",
    "source_file": "Исходник от организации",
    "ADMIN": "Администратор",
    "HEAD": "Руководитель отдела",
    "SYSTEM": "Система",
}

# These values remain useful for forensic storage, but add no information to
# the employee-facing diff because the object label, event author and event
# timestamp already provide their context.
HIDDEN_DIFF_FIELDS = {
    "id",
    "organization_id",
    "contract_id",
    "application_id",
    "additional_agreement_id",
    "order_id",
    "order_item_id",
    "document_id",
    "created_by",
    "updated_by",
    "uploaded_by",
    "created_at",
    "updated_at",
    "uploaded_at",
    "revision",
    "version",
}

# Foreign keys which carry business meaning and therefore remain visible.
REFERENCE_FIELDS = {
    "organization_id": "organization",
    "contract_id": "contract",
    "application_id": "application",
    "additional_agreement_id": "additional_agreement",
    "previous_agreement_id": "additional_agreement",
    "previous_order_id": "order",
    "order_id": "order",
    "order_item_id": "order_item",
    "specialty_id": "specialty",
    "faculty_id": "faculty",
    "created_by": "app_user",
    "updated_by": "app_user",
    "uploaded_by": "app_user",
    "document_id": "document",
    "source_order_id": "order",
    "target_order_id": "order",
}

