BEGIN;
CREATE TABLE IF NOT EXISTS app_user (id bigserial PRIMARY KEY, username varchar(100) NOT NULL UNIQUE, password_hash varchar(255) NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS faculty (id bigserial PRIMARY KEY, name varchar(255) NOT NULL UNIQUE, code varchar(30) UNIQUE);
CREATE TABLE IF NOT EXISTS organization (id bigserial PRIMARY KEY, unp varchar(9) NOT NULL UNIQUE, short_name varchar(255) NOT NULL, full_name text NOT NULL, legal_address text, authority varchar(255), phone varchar(50));
CREATE TABLE IF NOT EXISTS organization_representative (id bigserial PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organization(id) ON DELETE CASCADE, full_name varchar(255) NOT NULL, position varchar(255), phone varchar(50), authority_basis text);
CREATE INDEX IF NOT EXISTS idx_representative_organization ON organization_representative(organization_id);
CREATE TABLE IF NOT EXISTS contract (id bigserial PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organization(id) ON DELETE CASCADE, faculty_id bigint NOT NULL REFERENCES faculty(id), number varchar(100) NOT NULL, start_date date NOT NULL, end_date date, status varchar(30) NOT NULL DEFAULT 'ACTIVE', CONSTRAINT uq_contract_number UNIQUE(organization_id, number, faculty_id));
CREATE INDEX IF NOT EXISTS idx_contract_organization ON contract(organization_id);
CREATE INDEX IF NOT EXISTS idx_contract_faculty ON contract(faculty_id);
CREATE TABLE IF NOT EXISTS additional_agreement (id bigserial PRIMARY KEY, contract_id bigint NOT NULL REFERENCES contract(id) ON DELETE CASCADE, number varchar(100) NOT NULL, date date NOT NULL, CONSTRAINT uq_agreement_number UNIQUE(contract_id, number));
CREATE INDEX IF NOT EXISTS idx_agreement_contract ON additional_agreement(contract_id);
CREATE TABLE IF NOT EXISTS specialty (id bigserial PRIMARY KEY, code varchar(50) NOT NULL UNIQUE, name varchar(255) NOT NULL, qualification varchar(255), faculty varchar(255));
CREATE TABLE IF NOT EXISTS orders (id bigserial PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organization(id) ON DELETE CASCADE, contract_id bigint REFERENCES contract(id) ON DELETE SET NULL, status varchar(30) NOT NULL DEFAULT 'DRAFT', created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by bigint NOT NULL REFERENCES app_user(id));
CREATE INDEX IF NOT EXISTS idx_order_organization ON orders(organization_id);
CREATE INDEX IF NOT EXISTS idx_order_contract ON orders(contract_id);
CREATE TABLE IF NOT EXISTS order_item (id bigserial PRIMARY KEY, order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE, specialty_id bigint NOT NULL REFERENCES specialty(id), CONSTRAINT uq_order_specialty UNIQUE(order_id, specialty_id));
CREATE INDEX IF NOT EXISTS idx_order_item_order ON order_item(order_id);
CREATE TABLE IF NOT EXISTS annual_demand (id bigserial PRIMARY KEY, order_item_id bigint NOT NULL REFERENCES order_item(id) ON DELETE CASCADE, year integer NOT NULL, quantity integer NOT NULL, CONSTRAINT uq_annual_demand UNIQUE(order_item_id, year));
CREATE INDEX IF NOT EXISTS idx_annual_demand_order_item ON annual_demand(order_item_id);
CREATE TABLE IF NOT EXISTS document (id bigserial PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organization(id) ON DELETE CASCADE, contract_id bigint REFERENCES contract(id) ON DELETE SET NULL, type varchar(50) NOT NULL, version integer NOT NULL DEFAULT 1, status varchar(30) NOT NULL DEFAULT 'DRAFT', created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, file_id varchar(255));
CREATE INDEX IF NOT EXISTS idx_document_organization ON document(organization_id);
CREATE INDEX IF NOT EXISTS idx_document_contract ON document(contract_id);
INSERT INTO app_user(username, password_hash) VALUES ('demo', 'not-used-in-demo') ON CONFLICT(username) DO NOTHING;
COMMIT;
